[tool.ruff]
src = ["."]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "N",  # pep8-naming
    "D",  # pydocstyle
    "PT",  # flake8-pytest-style
    "RUF",  # Ruff-specific rules
]

ignore = [
    "D100",  # Missing docstring in public module
    "D104",  # Missing docstring in public package
    "D102",  # Missing docstring in public methods
]

[tool.ruff.lint.isort]
known-first-party = ["assistant", "implementations", "interfaces"]

[tool.ruff.lint.per-file-ignores]
"surface.ipynb" = ["E402"]  # Only ignore import order in notebooks