line-length = 88
indent-width = 4

target-version = "py312"
include = ["*.py", "*.pyi", "*.ipynb"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[lint]
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "N",   # pep8-naming
    "D",   # pydocstyle
    "PT",  # flake8-pytest-style
    "RUF", # Ruff-specific rules
]

ignore = [
    "D100",  # Missing docstring in public module
    "D104",  # Missing docstring in public package
    "D102",  # Missing docstring in public methods
]

[lint.isort]
combine-as-imports = true
lines-after-imports = 2
known-first-party = ["assistant", "implementations", "interfaces"]

[lint.pydocstyle]
convention = "google"

[lint.per-file-ignores]
"surface.ipynb" = ["E402"]  # Only ignore import order in notebooks 